import type { Locale } from './config';

export type Dictionary = typeof en;
const en = {
  meta:{title:'Repo2Skill — Turn GitHub repositories into professional AI Skills',description:'Analyze a public GitHub repository and export repository-native Skills for ChatGPT and Claude without paid AI APIs.',ogTitle:'Turn a GitHub repo into a professional AI Skill',ogDescription:'Architecture-aware, command-aware, test-aware Agent Skills generated from real repository evidence.'},
  nav:{product:'Repo2Skill',tag:'GitHub → AI Skill',language:'Language'},
  hero:{badge:'ZERO PAID AI API · REPOSITORY-NATIVE',titleA:'Turn a GitHub repo into a',titleB:'serious engineering Skill.',subtitle:'Repo2Skill maps architecture, commands, dependencies, APIs, tests, CI and code structure, then packages two repository-native Skills: ChatGPT and Claude.',free:'No OpenAI / Anthropic API',browser:'Browser-first analysis',languages:'7-language interface'},
  studio:{stepSource:'1 · Repository',stepReview:'2 · Intelligence',stepExport:'3 · Export',sourceTitle:'Give it a public GitHub repository',sourceText:'Repo2Skill reads the repository tree and a prioritized set of high-signal files directly from GitHub in your browser.',urlLabel:'GitHub repository',urlPlaceholder:'https://github.com/owner/repository',analyze:'Analyze repository',analyzing:'Analyzing…',depth:'Analysis depth',focused:'Focused',focusedHint:'Faster · key files',deep:'Deep',deepHint:'Recommended · broader evidence',publicOnly:'Public repositories only in this zero-cost build.',reviewTitle:'Repository intelligence',reviewText:'Review what Repo2Skill actually detected before compiling the Skills.',repoType:'Repository type',language:'Primary language',files:'Files analyzed',coverage:'Evidence coverage',frameworks:'Frameworks & tools',commands:'Commands',tests:'Tests',endpoints:'API routes',ci:'CI workflows',skillName:'Skill name',skillNamePlaceholder:'repository-engineer',focus:'Optional specialization',focusPlaceholder:'e.g. Focus heavily on backend API implementation, performance and safe migrations.',generate:'Compile professional Skills',reset:'Start over',exportTitle:'Two professional Skill packages are ready',exportText:'Each package uses a compact SKILL.md plus progressive-disclosure references generated from the repository evidence.',chatgpt:'ChatGPT Work Skill',claude:'Claude Skill',chatgptText:'Repository-native engineering workflow with implementation, debugging, review, testing, refactoring and migration modes.',claudeText:'Progressive-disclosure repository engineer optimized for Claude Skills.',download:'Download ZIP',downloadBoth:'Download both',noApi:'No paid AI API',localZip:'ZIPs built in browser',publicRepo:'Public repo evidence',sourceGuard:'Untrusted-source boundary'},
  how:{eyebrow:'What makes the Skill professional',title:'Not a README summary. An engineering operating system.',oneTitle:'Repository fingerprint',oneText:'Detect repo shape, language, frameworks, package managers, manifests, commands, environment signals and important code areas.',twoTitle:'Engineering map',twoText:'Extract routes, exported symbols, tests, CI, dependencies, conventions and source excerpts with exact repository paths.',threeTitle:'Repository-native playbooks',threeText:'Compile implement, debug, review, test, explain, refactor and migration protocols with validation and source-of-truth rules.'},
  faq:{title:'Common questions',q1:'Does this use an AI API to analyze my repository?',a1:'No. This build uses deterministic browser-side analysis of GitHub metadata, the recursive tree and selected raw files. That keeps recurring AI API cost at zero.',q2:'Will the Skill know the entire repository?',a2:'It builds a bounded evidence snapshot, not a perfect semantic index. Deep mode fetches more high-signal files and includes a file index plus source excerpts. When a live repository is available, the Skill is instructed to prefer current files over the snapshot.',q3:'What makes the output specialized?',a3:'The Skill is generated from the repository’s real commands, architecture signals, dependencies, routes, symbols, tests, CI and conventions. It also has task-specific protocols for implementation, debugging, review, testing, refactoring and migrations.'},
  footer:{line:'From repository evidence to a portable engineering Skill.',openSource:'MIT licensed',zeroCost:'Zero paid AI API'},
  status:{invalid:'Enter a valid public GitHub repository URL or owner/repo.',notFound:'Repository not found or not public.',rate:'GitHub rate limit reached for this browser/IP. Try again after the reset window.',failed:'Repository analysis failed. Check the URL and try again.',ready:'Repository analysis complete.',generated:'Both professional Skill packages were generated in your browser.',insufficient:'GitHub returned too little readable source content for a useful Skill.'}
};
const fa:Dictionary = {
  meta:{title:'Repo2Skill — تبدیل ریپوی GitHub به اسکیل حرفه‌ای هوش مصنوعی',description:'یک ریپوی عمومی GitHub را تحلیل کنید و بدون API پولی، اسکیل‌های تخصصی برای ChatGPT و Claude بسازید.',ogTitle:'ریپوی GitHub را به یک اسکیل حرفه‌ای تبدیل کنید',ogDescription:'اسکیل‌های Agent آگاه از معماری، دستورات، تست‌ها و ساختار واقعی ریپو.'},
  nav:{product:'Repo2Skill',tag:'GitHub ← AI Skill',language:'زبان'},
  hero:{badge:'بدون API پولی · REPOSITORY-NATIVE',titleA:'یک ریپوی GitHub را به',titleB:'اسکیل مهندسی جدی تبدیل کن.',subtitle:'Repo2Skill معماری، دستورات، وابستگی‌ها، APIها، تست‌ها، CI و ساختار کد را استخراج می‌کند و دو اسکیل تخصصی برای ChatGPT و Claude می‌سازد.',free:'بدون API OpenAI / Anthropic',browser:'تحلیل در مرورگر',languages:'رابط ۷ زبانه'},
  studio:{stepSource:'۱ · ریپو',stepReview:'۲ · تحلیل',stepExport:'۳ · خروجی',sourceTitle:'لینک یک ریپوی عمومی GitHub را بده',sourceText:'Repo2Skill ساختار ریپو و فایل‌های مهم را مستقیماً از GitHub و داخل مرورگر شما می‌خواند.',urlLabel:'ریپوی GitHub',urlPlaceholder:'https://github.com/owner/repository',analyze:'تحلیل ریپو',analyzing:'در حال تحلیل…',depth:'عمق تحلیل',focused:'متمرکز',focusedHint:'سریع‌تر · فایل‌های اصلی',deep:'عمیق',deepHint:'پیشنهادی · شواهد بیشتر',publicOnly:'این نسخه رایگان فقط ریپوهای عمومی را تحلیل می‌کند.',reviewTitle:'هوش استخراج‌شده از ریپو',reviewText:'قبل از ساخت اسکیل ببین Repo2Skill واقعاً چه چیزهایی را تشخیص داده است.',repoType:'نوع ریپو',language:'زبان اصلی',files:'فایل‌های تحلیل‌شده',coverage:'پوشش شواهد',frameworks:'فریم‌ورک‌ها و ابزارها',commands:'دستورات',tests:'تست‌ها',endpoints:'مسیرهای API',ci:'Workflowهای CI',skillName:'نام اسکیل',skillNamePlaceholder:'repository-engineer',focus:'تخصص اختیاری',focusPlaceholder:'مثلاً تمرکز ویژه روی backend API، performance و migration امن.',generate:'ساخت اسکیل‌های حرفه‌ای',reset:'شروع دوباره',exportTitle:'دو پکیج حرفه‌ای آماده‌اند',exportText:'هر خروجی یک SKILL.md فشرده و مجموعه referenceهای تخصصی مبتنی بر شواهد واقعی ریپو دارد.',chatgpt:'اسکیل ChatGPT Work',claude:'اسکیل Claude',chatgptText:'مهندس repository-native با حالت‌های پیاده‌سازی، دیباگ، review، تست، refactor و migration.',claudeText:'مهندس تخصصی ریپو با progressive disclosure بهینه برای Claude Skills.',download:'دانلود ZIP',downloadBoth:'دانلود هر دو',noApi:'بدون API پولی',localZip:'ساخت ZIP در مرورگر',publicRepo:'شواهد ریپوی عمومی',sourceGuard:'مرز اعتماد منبع'},
  how:{eyebrow:'چرا اسکیل حرفه‌ای است',title:'خلاصه README نیست؛ سیستم‌عامل مهندسی همان ریپو است.',oneTitle:'اثر انگشت ریپو',oneText:'نوع پروژه، زبان، فریم‌ورک، package manager، manifestها، دستورات، env و نواحی مهم کد تشخیص داده می‌شوند.',twoTitle:'نقشه مهندسی',twoText:'routeها، symbolها، تست‌ها، CI، dependencyها، conventionها و source excerptها با مسیر دقیق فایل استخراج می‌شوند.',threeTitle:'Playbookهای repository-native',threeText:'پروتکل‌های Implement، Debug، Review، Test، Explain، Refactor و Migration همراه با validation و hierarchy منبع ساخته می‌شوند.'},
  faq:{title:'سؤال‌های رایج',q1:'برای تحلیل ریپو از API هوش مصنوعی استفاده می‌شود؟',a1:'خیر. تحلیل این نسخه قطعی و داخل مرورگر است و از metadata، tree و فایل‌های منتخب GitHub استفاده می‌کند؛ هزینه API هوش مصنوعی صفر می‌ماند.',q2:'اسکیل کل ریپو را می‌فهمد؟',a2:'یک snapshot محدود اما پرسیگنال می‌سازد، نه index معنایی کامل. حالت Deep فایل‌های مهم بیشتری می‌گیرد و file index و source excerpt دارد. اگر ریپوی زنده در دسترس باشد، اسکیل موظف است فایل‌های فعلی را بر snapshot ترجیح دهد.',q3:'چرا خروجی تخصصی است؟',a3:'چون از دستورات واقعی، معماری، dependencyها، routeها، symbolها، تست‌ها، CI و conventionهای همان ریپو ساخته می‌شود و برای کارهای مهندسی playbook جدا دارد.'},
  footer:{line:'از شواهد ریپو تا یک اسکیل مهندسی قابل‌حمل.',openSource:'مجوز MIT',zeroCost:'بدون API پولی'},
  status:{invalid:'یک URL معتبر GitHub یا owner/repo وارد کنید.',notFound:'ریپو پیدا نشد یا عمومی نیست.',rate:'محدودیت GitHub برای این مرورگر/IP پر شده است؛ بعد از reset دوباره امتحان کنید.',failed:'تحلیل ریپو ناموفق بود. لینک را بررسی کنید.',ready:'تحلیل ریپو کامل شد.',generated:'هر دو پکیج حرفه‌ای داخل مرورگر ساخته شدند.',insufficient:'GitHub محتوای قابل‌خواندن کافی برای ساخت یک اسکیل مفید برنگرداند.'}
};
const ar:Dictionary = {
  meta:{title:'Repo2Skill — حوّل مستودع GitHub إلى Skill احترافية',description:'حلّل مستودع GitHub عامًا وصدّر Skills متخصصة لـ ChatGPT وClaude بدون API ذكاء اصطناعي مدفوعة.',ogTitle:'حوّل مستودع GitHub إلى Skill هندسية احترافية',ogDescription:'Skills واعية بالمعمارية والأوامر والاختبارات وبنية المستودع الحقيقية.'},
  nav:{product:'Repo2Skill',tag:'GitHub ← AI Skill',language:'اللغة'},
  hero:{badge:'بدون API مدفوعة · REPOSITORY-NATIVE',titleA:'حوّل مستودع GitHub إلى',titleB:'Skill هندسية حقيقية.',subtitle:'يرسم Repo2Skill المعمارية والأوامر والتبعيات وواجهات API والاختبارات وCI وبنية الكود، ثم ينشئ Skill لـ ChatGPT وأخرى لـ Claude.',free:'بدون OpenAI / Anthropic API',browser:'تحليل داخل المتصفح',languages:'واجهة بـ 7 لغات'},
  studio:{stepSource:'1 · المستودع',stepReview:'2 · التحليل',stepExport:'3 · التصدير',sourceTitle:'أدخل مستودع GitHub عامًا',sourceText:'يقرأ Repo2Skill شجرة المستودع والملفات الأعلى قيمة مباشرة من GitHub داخل متصفحك.',urlLabel:'مستودع GitHub',urlPlaceholder:'https://github.com/owner/repository',analyze:'تحليل المستودع',analyzing:'جارٍ التحليل…',depth:'عمق التحليل',focused:'مركّز',focusedHint:'أسرع · الملفات الأساسية',deep:'عميق',deepHint:'موصى به · أدلة أوسع',publicOnly:'هذه النسخة المجانية تدعم المستودعات العامة فقط.',reviewTitle:'ذكاء المستودع',reviewText:'راجع ما تم اكتشافه فعليًا قبل تجميع Skills.',repoType:'نوع المستودع',language:'اللغة الأساسية',files:'ملفات محللة',coverage:'تغطية الأدلة',frameworks:'الأطر والأدوات',commands:'الأوامر',tests:'الاختبارات',endpoints:'مسارات API',ci:'تدفقات CI',skillName:'اسم Skill',skillNamePlaceholder:'repository-engineer',focus:'تخصص اختياري',focusPlaceholder:'مثال: التركيز على backend API والأداء والترحيلات الآمنة.',generate:'إنشاء Skills احترافية',reset:'ابدأ من جديد',exportTitle:'حزمتا Skill جاهزتان',exportText:'كل حزمة تحتوي SKILL.md مضغوطًا ومراجع متخصصة مبنية على أدلة المستودع.',chatgpt:'Skill لـ ChatGPT Work',claude:'Skill لـ Claude',chatgptText:'مهندس خاص بالمستودع للتنفيذ والتصحيح والمراجعة والاختبار وإعادة الهيكلة والترحيل.',claudeText:'مهندس مستودع باستخدام progressive disclosure ومحسّن لـ Claude Skills.',download:'تنزيل ZIP',downloadBoth:'تنزيل الاثنين',noApi:'بدون API مدفوعة',localZip:'إنشاء ZIP في المتصفح',publicRepo:'أدلة مستودع عام',sourceGuard:'حد ثقة للمصدر'},
  how:{eyebrow:'ما الذي يجعل Skill احترافية',title:'ليست ملخص README، بل نظام عمل هندسي للمستودع.',oneTitle:'بصمة المستودع',oneText:'كشف شكل المشروع واللغة والأطر ومدير الحزم والـ manifests والأوامر وإشارات البيئة ومناطق الكود المهمة.',twoTitle:'خريطة هندسية',twoText:'استخراج routes وsymbols والاختبارات وCI والتبعيات والاتفاقيات ومقتطفات المصدر مع مسارات الملفات.',threeTitle:'Playbooks خاصة بالمستودع',threeText:'بروتوكولات Implement وDebug وReview وTest وExplain وRefactor وMigration مع validation وتسلسل مصادر الحقيقة.'},
  faq:{title:'أسئلة شائعة',q1:'هل يستخدم API ذكاء اصطناعي لتحليل المستودع؟',a1:'لا. التحليل حتمي داخل المتصفح باستخدام بيانات GitHub وشجرة الملفات وملفات خام مختارة، لذا لا توجد تكلفة API ذكاء اصطناعي.',q2:'هل تعرف Skill المستودع بالكامل؟',a2:'تنشئ snapshot محدودًا عالي الإشارة، وليس فهرسًا دلاليًا كاملاً. الوضع Deep يجلب ملفات مهمة أكثر مع فهرس ومقتطفات. وعند توفر المستودع الحي يجب تفضيله.',q3:'لماذا المخرجات متخصصة؟',a3:'لأنها مبنية على أوامر المستودع ومعماريته وتبعياته وroutes وsymbols والاختبارات وCI والاتفاقيات، مع بروتوكولات هندسية منفصلة.'},
  footer:{line:'من أدلة المستودع إلى Skill هندسية قابلة للنقل.',openSource:'ترخيص MIT',zeroCost:'بدون API مدفوعة'},
  status:{invalid:'أدخل رابط GitHub عامًا صحيحًا أو owner/repo.',notFound:'المستودع غير موجود أو غير عام.',rate:'تم بلوغ حد GitHub لهذا المتصفح/IP. حاول بعد فترة إعادة الضبط.',failed:'فشل تحليل المستودع. تحقق من الرابط.',ready:'اكتمل تحليل المستودع.',generated:'تم إنشاء حزمتَي Skill داخل المتصفح.',insufficient:'لم يُرجع GitHub محتوى مقروءًا كافيًا لإنشاء Skill مفيدة.'}
};
const zh:Dictionary = {
  meta:{title:'Repo2Skill — 将 GitHub 仓库转换为专业 AI Skill',description:'分析公开 GitHub 仓库，无需付费 AI API，即可导出 ChatGPT 与 Claude 专业 Skill。',ogTitle:'把 GitHub 仓库变成专业工程 Skill',ogDescription:'基于真实仓库架构、命令、测试、CI 与代码证据生成 Agent Skills。'},
  nav:{product:'Repo2Skill',tag:'GitHub → AI Skill',language:'语言'},
  hero:{badge:'零付费 AI API · REPOSITORY-NATIVE',titleA:'把 GitHub 仓库变成',titleB:'真正专业的工程 Skill。',subtitle:'Repo2Skill 映射架构、命令、依赖、API、测试、CI 和代码结构，然后分别打包 ChatGPT 与 Claude Skill。',free:'无需 OpenAI / Anthropic API',browser:'浏览器优先分析',languages:'7 种界面语言'},
  studio:{stepSource:'1 · 仓库',stepReview:'2 · 智能分析',stepExport:'3 · 导出',sourceTitle:'输入一个公开 GitHub 仓库',sourceText:'Repo2Skill 在你的浏览器中直接读取 GitHub 仓库树和高价值文件。',urlLabel:'GitHub 仓库',urlPlaceholder:'https://github.com/owner/repository',analyze:'分析仓库',analyzing:'分析中…',depth:'分析深度',focused:'聚焦',focusedHint:'更快 · 关键文件',deep:'深度',deepHint:'推荐 · 更多证据',publicOnly:'此零成本版本仅支持公开仓库。',reviewTitle:'仓库智能',reviewText:'编译 Skill 前先检查 Repo2Skill 实际检测到的内容。',repoType:'仓库类型',language:'主要语言',files:'已分析文件',coverage:'证据覆盖度',frameworks:'框架与工具',commands:'命令',tests:'测试',endpoints:'API 路由',ci:'CI 工作流',skillName:'Skill 名称',skillNamePlaceholder:'repository-engineer',focus:'可选专业方向',focusPlaceholder:'例如：重点关注后端 API、性能和安全迁移。',generate:'编译专业 Skills',reset:'重新开始',exportTitle:'两个专业 Skill 包已就绪',exportText:'每个包都包含精简 SKILL.md 与基于仓库证据生成的渐进式参考资料。',chatgpt:'ChatGPT Work Skill',claude:'Claude Skill',chatgptText:'面向该仓库的工程工作流：实现、调试、审查、测试、重构和迁移。',claudeText:'为 Claude Skills 优化的渐进式仓库工程师。',download:'下载 ZIP',downloadBoth:'下载两个',noApi:'无付费 AI API',localZip:'浏览器生成 ZIP',publicRepo:'公开仓库证据',sourceGuard:'不可信来源边界'},
  how:{eyebrow:'为什么它更专业',title:'不是 README 摘要，而是仓库级工程操作系统。',oneTitle:'仓库指纹',oneText:'检测项目形态、语言、框架、包管理器、manifest、命令、环境信号和关键代码区域。',twoTitle:'工程地图',twoText:'提取路由、导出符号、测试、CI、依赖、约定和带精确路径的源码摘录。',threeTitle:'仓库原生 Playbook',threeText:'生成 Implement、Debug、Review、Test、Explain、Refactor 与 Migration 协议，并包含验证和事实层级规则。'},
  faq:{title:'常见问题',q1:'分析仓库会调用 AI API 吗？',a1:'不会。本版本在浏览器端对 GitHub metadata、递归 tree 和选定 raw 文件做确定性分析，因此没有持续 AI API 成本。',q2:'Skill 会了解整个仓库吗？',a2:'它创建的是高信号、有限的证据快照，不是完整语义索引。Deep 模式会读取更多关键文件，并包含文件索引和源码摘录；有实时仓库时优先使用实时文件。',q3:'为什么输出是专业化的？',a3:'因为 Skill 来自仓库真实命令、架构信号、依赖、路由、符号、测试、CI 和约定，并包含不同工程任务的专门协议。'},
  footer:{line:'从仓库证据到可移植的工程 Skill。',openSource:'MIT 许可',zeroCost:'零付费 AI API'},
  status:{invalid:'请输入有效的公开 GitHub URL 或 owner/repo。',notFound:'仓库不存在或不是公开仓库。',rate:'此浏览器/IP 已达到 GitHub 限额，请在重置后重试。',failed:'仓库分析失败，请检查 URL。',ready:'仓库分析完成。',generated:'两个专业 Skill 包已在浏览器中生成。',insufficient:'GitHub 返回的可读源码不足，无法生成有价值的 Skill。'}
};
const fr:Dictionary = {
  meta:{title:'Repo2Skill — Transformez un dépôt GitHub en Skill IA professionnelle',description:'Analysez un dépôt GitHub public et exportez des Skills spécialisées pour ChatGPT et Claude sans API IA payante.',ogTitle:'Transformez un dépôt GitHub en Skill d’ingénierie',ogDescription:'Des Agent Skills basées sur l’architecture, les commandes, les tests, la CI et le code réel.'},
  nav:{product:'Repo2Skill',tag:'GitHub → AI Skill',language:'Langue'},
  hero:{badge:'ZÉRO API IA PAYANTE · REPOSITORY-NATIVE',titleA:'Transformez un dépôt GitHub en',titleB:'véritable Skill d’ingénierie.',subtitle:'Repo2Skill cartographie architecture, commandes, dépendances, API, tests, CI et structure du code, puis génère une Skill ChatGPT et une Skill Claude.',free:'Aucune API OpenAI / Anthropic',browser:'Analyse dans le navigateur',languages:'Interface en 7 langues'},
  studio:{stepSource:'1 · Dépôt',stepReview:'2 · Intelligence',stepExport:'3 · Export',sourceTitle:'Donnez un dépôt GitHub public',sourceText:'Repo2Skill lit l’arbre du dépôt et des fichiers à forte valeur directement depuis GitHub dans votre navigateur.',urlLabel:'Dépôt GitHub',urlPlaceholder:'https://github.com/owner/repository',analyze:'Analyser le dépôt',analyzing:'Analyse…',depth:'Profondeur',focused:'Ciblée',focusedHint:'Plus rapide · fichiers clés',deep:'Profonde',deepHint:'Recommandée · plus de preuves',publicOnly:'Cette version zéro coût analyse uniquement les dépôts publics.',reviewTitle:'Intelligence du dépôt',reviewText:'Vérifiez ce que Repo2Skill a réellement détecté avant la compilation.',repoType:'Type de dépôt',language:'Langage principal',files:'Fichiers analysés',coverage:'Couverture des preuves',frameworks:'Frameworks et outils',commands:'Commandes',tests:'Tests',endpoints:'Routes API',ci:'Workflows CI',skillName:'Nom de la Skill',skillNamePlaceholder:'repository-engineer',focus:'Spécialisation optionnelle',focusPlaceholder:'ex. Accent sur les API backend, les performances et les migrations sûres.',generate:'Compiler des Skills professionnelles',reset:'Recommencer',exportTitle:'Deux packages Skill professionnels sont prêts',exportText:'Chaque package contient un SKILL.md compact et des références en progressive disclosure dérivées du dépôt.',chatgpt:'Skill ChatGPT Work',claude:'Skill Claude',chatgptText:'Workflow d’ingénierie natif au dépôt pour implémentation, debug, review, tests, refactor et migration.',claudeText:'Ingénieur de dépôt en progressive disclosure optimisé pour Claude Skills.',download:'Télécharger ZIP',downloadBoth:'Télécharger les deux',noApi:'Aucune API IA payante',localZip:'ZIP créés dans le navigateur',publicRepo:'Preuves du dépôt public',sourceGuard:'Frontière de confiance'},
  how:{eyebrow:'Pourquoi la Skill est professionnelle',title:'Pas un résumé de README. Un système d’exploitation d’ingénierie.',oneTitle:'Empreinte du dépôt',oneText:'Détecte forme du projet, langage, frameworks, gestionnaires de paquets, manifests, commandes, environnement et zones de code importantes.',twoTitle:'Carte d’ingénierie',twoText:'Extrait routes, symboles, tests, CI, dépendances, conventions et extraits source avec chemins exacts.',threeTitle:'Playbooks natifs au dépôt',threeText:'Compile des protocoles Implement, Debug, Review, Test, Explain, Refactor et Migration avec validation et hiérarchie des sources.'},
  faq:{title:'Questions fréquentes',q1:'L’analyse utilise-t-elle une API IA ?',a1:'Non. Cette version effectue une analyse déterministe dans le navigateur à partir des métadonnées GitHub, de l’arbre récursif et de fichiers bruts sélectionnés.',q2:'La Skill connaît-elle tout le dépôt ?',a2:'Elle crée un snapshot borné à fort signal, pas un index sémantique parfait. Le mode Deep récupère plus de fichiers clés et inclut index et extraits. Si le dépôt live est disponible, il a priorité.',q3:'Pourquoi la sortie est-elle spécialisée ?',a3:'Parce qu’elle est construite à partir des commandes, de l’architecture, des dépendances, des routes, symboles, tests, CI et conventions réelles du dépôt, avec des protocoles d’ingénierie dédiés.'},
  footer:{line:'Des preuves du dépôt à une Skill d’ingénierie portable.',openSource:'Licence MIT',zeroCost:'Zéro API IA payante'},
  status:{invalid:'Saisissez une URL GitHub publique valide ou owner/repo.',notFound:'Dépôt introuvable ou non public.',rate:'Limite GitHub atteinte pour ce navigateur/IP. Réessayez après la réinitialisation.',failed:'Échec de l’analyse du dépôt. Vérifiez l’URL.',ready:'Analyse du dépôt terminée.',generated:'Les deux packages professionnels ont été générés dans votre navigateur.',insufficient:'GitHub n’a pas renvoyé assez de contenu lisible pour une Skill utile.'}
};
const es:Dictionary = {
  meta:{title:'Repo2Skill — Convierte repositorios GitHub en Skills IA profesionales',description:'Analiza un repositorio público de GitHub y exporta Skills especializadas para ChatGPT y Claude sin APIs de IA de pago.',ogTitle:'Convierte un repo GitHub en una Skill de ingeniería',ogDescription:'Agent Skills basadas en arquitectura, comandos, tests, CI y código real del repositorio.'},
  nav:{product:'Repo2Skill',tag:'GitHub → AI Skill',language:'Idioma'},
  hero:{badge:'CERO API IA DE PAGO · REPOSITORY-NATIVE',titleA:'Convierte un repo GitHub en una',titleB:'Skill de ingeniería de verdad.',subtitle:'Repo2Skill mapea arquitectura, comandos, dependencias, APIs, tests, CI y estructura del código y genera una Skill para ChatGPT y otra para Claude.',free:'Sin API OpenAI / Anthropic',browser:'Análisis en el navegador',languages:'Interfaz en 7 idiomas'},
  studio:{stepSource:'1 · Repositorio',stepReview:'2 · Inteligencia',stepExport:'3 · Exportar',sourceTitle:'Introduce un repositorio público de GitHub',sourceText:'Repo2Skill lee el árbol y archivos de alta señal directamente desde GitHub en tu navegador.',urlLabel:'Repositorio GitHub',urlPlaceholder:'https://github.com/owner/repository',analyze:'Analizar repositorio',analyzing:'Analizando…',depth:'Profundidad',focused:'Enfocado',focusedHint:'Más rápido · archivos clave',deep:'Profundo',deepHint:'Recomendado · más evidencia',publicOnly:'Esta versión sin coste analiza solo repositorios públicos.',reviewTitle:'Inteligencia del repositorio',reviewText:'Revisa lo que Repo2Skill detectó realmente antes de compilar.',repoType:'Tipo de repo',language:'Lenguaje principal',files:'Archivos analizados',coverage:'Cobertura de evidencia',frameworks:'Frameworks y herramientas',commands:'Comandos',tests:'Tests',endpoints:'Rutas API',ci:'Workflows CI',skillName:'Nombre de la Skill',skillNamePlaceholder:'repository-engineer',focus:'Especialización opcional',focusPlaceholder:'p. ej. centrarse en APIs backend, rendimiento y migraciones seguras.',generate:'Compilar Skills profesionales',reset:'Empezar de nuevo',exportTitle:'Dos paquetes Skill profesionales están listos',exportText:'Cada paquete usa un SKILL.md compacto y referencias de divulgación progresiva generadas desde el repo.',chatgpt:'Skill para ChatGPT Work',claude:'Skill para Claude',chatgptText:'Ingeniero nativo del repositorio para implementar, depurar, revisar, probar, refactorizar y migrar.',claudeText:'Ingeniero del repositorio con progressive disclosure optimizado para Claude Skills.',download:'Descargar ZIP',downloadBoth:'Descargar ambos',noApi:'Sin API IA de pago',localZip:'ZIP creados en el navegador',publicRepo:'Evidencia de repo público',sourceGuard:'Límite de confianza'},
  how:{eyebrow:'Por qué la Skill es profesional',title:'No es un resumen del README. Es un sistema operativo de ingeniería.',oneTitle:'Huella del repositorio',oneText:'Detecta forma del proyecto, lenguaje, frameworks, package managers, manifests, comandos, entorno y áreas importantes.',twoTitle:'Mapa de ingeniería',twoText:'Extrae rutas, símbolos, tests, CI, dependencias, convenciones y extractos con rutas exactas.',threeTitle:'Playbooks nativos del repo',threeText:'Compila protocolos de Implement, Debug, Review, Test, Explain, Refactor y Migration con validación y jerarquía de fuentes.'},
  faq:{title:'Preguntas frecuentes',q1:'¿Usa una API de IA para analizar el repo?',a1:'No. Esta versión hace análisis determinista en el navegador usando metadata, árbol recursivo y archivos raw seleccionados de GitHub.',q2:'¿La Skill conoce todo el repositorio?',a2:'Crea un snapshot limitado de alta señal, no un índice semántico perfecto. Deep obtiene más archivos clave e incluye índice y extractos. Si hay repo live, se prioriza.',q3:'¿Qué hace especializada la salida?',a3:'Se genera con comandos, arquitectura, dependencias, rutas, símbolos, tests, CI y convenciones reales del repositorio, más protocolos específicos por tarea.'},
  footer:{line:'De evidencia del repositorio a una Skill de ingeniería portable.',openSource:'Licencia MIT',zeroCost:'Cero API IA de pago'},
  status:{invalid:'Introduce una URL pública de GitHub válida o owner/repo.',notFound:'Repositorio no encontrado o no público.',rate:'Se alcanzó el límite de GitHub para este navegador/IP. Inténtalo tras el reinicio.',failed:'Falló el análisis. Revisa la URL.',ready:'Análisis del repositorio completado.',generated:'Ambos paquetes profesionales se generaron en tu navegador.',insufficient:'GitHub devolvió muy poco contenido legible para una Skill útil.'}
};
const it:Dictionary = {
  meta:{title:'Repo2Skill — Trasforma repository GitHub in Skill AI professionali',description:'Analizza un repository GitHub pubblico ed esporta Skill specialistiche per ChatGPT e Claude senza API AI a pagamento.',ogTitle:'Trasforma un repo GitHub in una Skill di engineering',ogDescription:'Agent Skill basate su architettura, comandi, test, CI e codice reale del repository.'},
  nav:{product:'Repo2Skill',tag:'GitHub → AI Skill',language:'Lingua'},
  hero:{badge:'ZERO API AI A PAGAMENTO · REPOSITORY-NATIVE',titleA:'Trasforma un repo GitHub in una',titleB:'vera Skill di engineering.',subtitle:'Repo2Skill mappa architettura, comandi, dipendenze, API, test, CI e struttura del codice, poi crea una Skill ChatGPT e una Claude.',free:'Nessuna API OpenAI / Anthropic',browser:'Analisi nel browser',languages:'Interfaccia in 7 lingue'},
  studio:{stepSource:'1 · Repository',stepReview:'2 · Intelligence',stepExport:'3 · Export',sourceTitle:'Inserisci un repository GitHub pubblico',sourceText:'Repo2Skill legge albero e file ad alto segnale direttamente da GitHub nel tuo browser.',urlLabel:'Repository GitHub',urlPlaceholder:'https://github.com/owner/repository',analyze:'Analizza repository',analyzing:'Analisi…',depth:'Profondità',focused:'Mirata',focusedHint:'Più veloce · file chiave',deep:'Profonda',deepHint:'Consigliata · più evidenze',publicOnly:'Questa build a costo zero analizza solo repository pubblici.',reviewTitle:'Repository intelligence',reviewText:'Controlla ciò che Repo2Skill ha davvero rilevato prima della compilazione.',repoType:'Tipo repository',language:'Linguaggio principale',files:'File analizzati',coverage:'Copertura evidenze',frameworks:'Framework e tool',commands:'Comandi',tests:'Test',endpoints:'Route API',ci:'Workflow CI',skillName:'Nome Skill',skillNamePlaceholder:'repository-engineer',focus:'Specializzazione opzionale',focusPlaceholder:'es. focus su backend API, performance e migrazioni sicure.',generate:'Compila Skill professionali',reset:'Ricomincia',exportTitle:'Due pacchetti Skill professionali sono pronti',exportText:'Ogni pacchetto usa SKILL.md compatto e riferimenti progressive-disclosure generati dalle evidenze del repo.',chatgpt:'Skill ChatGPT Work',claude:'Skill Claude',chatgptText:'Ingegnere repository-native per implementazione, debug, review, test, refactor e migrazione.',claudeText:'Ingegnere del repository con progressive disclosure ottimizzato per Claude Skills.',download:'Scarica ZIP',downloadBoth:'Scarica entrambi',noApi:'Nessuna API AI a pagamento',localZip:'ZIP creati nel browser',publicRepo:'Evidenze repo pubblico',sourceGuard:'Confine di fiducia'},
  how:{eyebrow:'Perché la Skill è professionale',title:'Non è un riassunto README. È un sistema operativo di engineering.',oneTitle:'Fingerprint repository',oneText:'Rileva forma del progetto, linguaggio, framework, package manager, manifest, comandi, ambiente e aree importanti.',twoTitle:'Mappa engineering',twoText:'Estrae route, symbol, test, CI, dipendenze, convenzioni e source excerpt con percorsi esatti.',threeTitle:'Playbook repository-native',threeText:'Compila protocolli Implement, Debug, Review, Test, Explain, Refactor e Migration con validation e gerarchia delle fonti.'},
  faq:{title:'Domande frequenti',q1:'Usa un’API AI per analizzare il repo?',a1:'No. Questa build usa analisi deterministica nel browser su metadata GitHub, tree ricorsivo e file raw selezionati.',q2:'La Skill conosce tutto il repository?',a2:'Crea uno snapshot limitato ad alto segnale, non un indice semantico perfetto. Deep legge più file chiave e include indice ed estratti. Se il repo live è disponibile ha priorità.',q3:'Perché l’output è specialistico?',a3:'Perché nasce da comandi, architettura, dipendenze, route, symbol, test, CI e convenzioni reali del repository, con protocolli dedicati per ogni tipo di lavoro.'},
  footer:{line:'Dalle evidenze del repository a una Skill di engineering portabile.',openSource:'Licenza MIT',zeroCost:'Zero API AI a pagamento'},
  status:{invalid:'Inserisci una URL GitHub pubblica valida o owner/repo.',notFound:'Repository non trovato o non pubblico.',rate:'Limite GitHub raggiunto per questo browser/IP. Riprova dopo il reset.',failed:'Analisi repository fallita. Controlla la URL.',ready:'Analisi repository completata.',generated:'Entrambi i pacchetti professionali sono stati creati nel browser.',insufficient:'GitHub non ha restituito abbastanza contenuto leggibile per una Skill utile.'}
};
export const dictionaries:Record<Locale,Dictionary>={en,fa,ar,zh,fr,es,it};
export function getDictionary(locale:Locale){ return dictionaries[locale]; }
